### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [bobandmermaid/form#5]
Отличная работа, все реализованно!

Единственное нужно сделать не большое исправление, что бы была корректная валидация данного домена(http://ya.ru:00000).

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
- Есть gitignore

**Надо исправить**
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Comment by bobandmermaid** [comment]
День добрый!
Поправил

**Comment by bobandmermaid** [comment]
Здравствуйте. Ссылку нужно ещё раз отправить?

**Comment by talantbekov123** [comment]
Хорошая работа, все комментарии исправлены! Похвально! Принимаю.

**Comment by talantbekov123** [comment]
Отличный readme, все подробно описали и работа выполнена очень хорошо.
